# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f36f2b8146adeacedb2686bffff48184e04d3e9f322213956cd50d4d0cfc78ed79157becd643b42173bf7a49576cd1280ce6b35625b2aaf035720a52368c4dfb

test:
  secret_key_base: b3d84f0f5d99c00e1ca6bee5b015275b219324d13b27f0c303645ef9a561ebdeef74e86d8e3460e6550901fbf94c7aa519d02725b445356183437450443a1599

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
